# Site settings
title: My Personal Webpage
email: marcos.horro@udc.es
description: > # this means to ignore newlines until "baseurl:"
  Just another personal webpage: Markos Horro
# baseurl: "/index" # the subpath of your site, e.g. /blog/
url: "http://marcoshorro.com" # the base hostname & protocol for your site
twitter_username: markoshorro
github_username: markoshorro

# Build settings
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

# Options for jekyll-multiple-languages-plugin
languages: ["en", "gl"]
exclude_from_localizations: ["assets", "css", "img", "fonts"]
